// Code generated by ent, DO NOT EDIT.

package auditevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the auditevent type in the database.
	Label = "audit_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldOutboxEventID holds the string denoting the outbox_event_id field in the database.
	FieldOutboxEventID = "outbox_event_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// EdgeOutboxEvent holds the string denoting the outbox_event edge name in mutations.
	EdgeOutboxEvent = "outbox_event"
	// Table holds the table name of the auditevent in the database.
	Table = "audit_events"
	// OutboxEventTable is the table that holds the outbox_event relation/edge.
	OutboxEventTable = "audit_events"
	// OutboxEventInverseTable is the table name for the OutboxEvent entity.
	// It exists in this package in order to avoid circular dependency with the "outboxevent" package.
	OutboxEventInverseTable = "outbox_events"
	// OutboxEventColumn is the table column denoting the outbox_event relation/edge.
	OutboxEventColumn = "outbox_event_id"
)

// Columns holds all SQL columns for auditevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldOutboxEventID,
	FieldEventType,
	FieldActorID,
	FieldOrganizationID,
	FieldResourceType,
	FieldResourceID,
	FieldPayload,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	ResourceTypeValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AuditEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByOutboxEventID orders the results by the outbox_event_id field.
func ByOutboxEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboxEventID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByActorID orders the results by the actor_id field.
func ByActorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByOutboxEventField orders the results by outbox_event field.
func ByOutboxEventField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOutboxEventStep(), sql.OrderByField(field, opts...))
	}
}
func newOutboxEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OutboxEventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OutboxEventTable, OutboxEventColumn),
	)
}
