// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/open-huddle/huddle/apps/api/ent/auditevent"
	"github.com/open-huddle/huddle/apps/api/ent/outboxevent"
)

// AuditEvent is the model entity for the AuditEvent schema.
type AuditEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// OutboxEventID holds the value of the "outbox_event_id" field.
	OutboxEventID uuid.UUID `json:"outbox_event_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID *uuid.UUID `json:"actor_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID *uuid.UUID `json:"organization_id,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID uuid.UUID `json:"resource_id,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload []byte `json:"payload,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AuditEventQuery when eager-loading is set.
	Edges        AuditEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AuditEventEdges holds the relations/edges for other nodes in the graph.
type AuditEventEdges struct {
	// OutboxEvent holds the value of the outbox_event edge.
	OutboxEvent *OutboxEvent `json:"outbox_event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OutboxEventOrErr returns the OutboxEvent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AuditEventEdges) OutboxEventOrErr() (*OutboxEvent, error) {
	if e.OutboxEvent != nil {
		return e.OutboxEvent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: outboxevent.Label}
	}
	return nil, &NotLoadedError{edge: "outbox_event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditevent.FieldActorID, auditevent.FieldOrganizationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case auditevent.FieldPayload:
			values[i] = new([]byte)
		case auditevent.FieldEventType, auditevent.FieldResourceType:
			values[i] = new(sql.NullString)
		case auditevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case auditevent.FieldID, auditevent.FieldOutboxEventID, auditevent.FieldResourceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditEvent fields.
func (_m *AuditEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case auditevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case auditevent.FieldOutboxEventID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field outbox_event_id", values[i])
			} else if value != nil {
				_m.OutboxEventID = *value
			}
		case auditevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case auditevent.FieldActorID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = new(uuid.UUID)
				*_m.ActorID = *value.S.(*uuid.UUID)
			}
		case auditevent.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = new(uuid.UUID)
				*_m.OrganizationID = *value.S.(*uuid.UUID)
			}
		case auditevent.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = value.String
			}
		case auditevent.FieldResourceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value != nil {
				_m.ResourceID = *value
			}
		case auditevent.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				_m.Payload = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditEvent.
// This includes values selected through modifiers, order, etc.
func (_m *AuditEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOutboxEvent queries the "outbox_event" edge of the AuditEvent entity.
func (_m *AuditEvent) QueryOutboxEvent() *OutboxEventQuery {
	return NewAuditEventClient(_m.config).QueryOutboxEvent(_m)
}

// Update returns a builder for updating this AuditEvent.
// Note that you need to call AuditEvent.Unwrap() before calling this method if this AuditEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditEvent) Update() *AuditEventUpdateOne {
	return NewAuditEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditEvent) Unwrap() *AuditEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AuditEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("outbox_event_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutboxEventID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	if v := _m.ActorID; v != nil {
		builder.WriteString("actor_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OrganizationID; v != nil {
		builder.WriteString("organization_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(_m.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceID))
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteByte(')')
	return builder.String()
}

// AuditEvents is a parsable slice of AuditEvent.
type AuditEvents []*AuditEvent
