// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/open-huddle/huddle/apps/api/ent/auditevent"
	"github.com/open-huddle/huddle/apps/api/ent/outboxevent"
)

// AuditEventCreate is the builder for creating a AuditEvent entity.
type AuditEventCreate struct {
	config
	mutation *AuditEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditEventCreate) SetCreatedAt(v time.Time) *AuditEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableCreatedAt(v *time.Time) *AuditEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetOutboxEventID sets the "outbox_event_id" field.
func (_c *AuditEventCreate) SetOutboxEventID(v uuid.UUID) *AuditEventCreate {
	_c.mutation.SetOutboxEventID(v)
	return _c
}

// SetNillableOutboxEventID sets the "outbox_event_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableOutboxEventID(v *uuid.UUID) *AuditEventCreate {
	if v != nil {
		_c.SetOutboxEventID(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *AuditEventCreate) SetEventType(v string) *AuditEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *AuditEventCreate) SetActorID(v uuid.UUID) *AuditEventCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableActorID(v *uuid.UUID) *AuditEventCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *AuditEventCreate) SetOrganizationID(v uuid.UUID) *AuditEventCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableOrganizationID(v *uuid.UUID) *AuditEventCreate {
	if v != nil {
		_c.SetOrganizationID(*v)
	}
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *AuditEventCreate) SetResourceType(v string) *AuditEventCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *AuditEventCreate) SetResourceID(v uuid.UUID) *AuditEventCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *AuditEventCreate) SetPayload(v []byte) *AuditEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AuditEventCreate) SetID(v uuid.UUID) *AuditEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableID(v *uuid.UUID) *AuditEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOutboxEvent sets the "outbox_event" edge to the OutboxEvent entity.
func (_c *AuditEventCreate) SetOutboxEvent(v *OutboxEvent) *AuditEventCreate {
	return _c.SetOutboxEventID(v.ID)
}

// Mutation returns the AuditEventMutation object of the builder.
func (_c *AuditEventCreate) Mutation() *AuditEventMutation {
	return _c.mutation
}

// Save creates the AuditEvent in the database.
func (_c *AuditEventCreate) Save(ctx context.Context) (*AuditEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEventCreate) SaveX(ctx context.Context) *AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := auditevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := auditevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditEvent.created_at"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "AuditEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := auditevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AuditEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "AuditEvent.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := auditevent.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AuditEvent.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "AuditEvent.resource_id"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "AuditEvent.payload"`)}
	}
	return nil
}

func (_c *AuditEventCreate) sqlSave(ctx context.Context) (*AuditEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEventCreate) createSpec() (*AuditEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditevent.Table, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(auditevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(auditevent.FieldActorID, field.TypeUUID, value)
		_node.ActorID = &value
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(auditevent.FieldOrganizationID, field.TypeUUID, value)
		_node.OrganizationID = &value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(auditevent.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(auditevent.FieldResourceID, field.TypeUUID, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(auditevent.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if nodes := _c.mutation.OutboxEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   auditevent.OutboxEventTable,
			Columns: []string{auditevent.OutboxEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OutboxEventID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditEventCreate) OnConflict(opts ...sql.ConflictOption) *AuditEventUpsertOne {
	_c.conflict = opts
	return &AuditEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditEventCreate) OnConflictColumns(columns ...string) *AuditEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditEventUpsertOne{
		create: _c,
	}
}

type (
	// AuditEventUpsertOne is the builder for "upsert"-ing
	//  one AuditEvent node.
	AuditEventUpsertOne struct {
		create *AuditEventCreate
	}

	// AuditEventUpsert is the "OnConflict" setter.
	AuditEventUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditEventUpsertOne) UpdateNewValues() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(auditevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(auditevent.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.OutboxEventID(); exists {
			s.SetIgnore(auditevent.FieldOutboxEventID)
		}
		if _, exists := u.create.mutation.EventType(); exists {
			s.SetIgnore(auditevent.FieldEventType)
		}
		if _, exists := u.create.mutation.ActorID(); exists {
			s.SetIgnore(auditevent.FieldActorID)
		}
		if _, exists := u.create.mutation.OrganizationID(); exists {
			s.SetIgnore(auditevent.FieldOrganizationID)
		}
		if _, exists := u.create.mutation.ResourceType(); exists {
			s.SetIgnore(auditevent.FieldResourceType)
		}
		if _, exists := u.create.mutation.ResourceID(); exists {
			s.SetIgnore(auditevent.FieldResourceID)
		}
		if _, exists := u.create.mutation.Payload(); exists {
			s.SetIgnore(auditevent.FieldPayload)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuditEventUpsertOne) Ignore() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditEventUpsertOne) DoNothing() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditEventCreate.OnConflict
// documentation for more info.
func (u *AuditEventUpsertOne) Update(set func(*AuditEventUpsert)) *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuditEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuditEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuditEventUpsertOne.ID is not supported by MySQL driver. Use AuditEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuditEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuditEventCreateBulk is the builder for creating many AuditEvent entities in bulk.
type AuditEventCreateBulk struct {
	config
	err      error
	builders []*AuditEventCreate
	conflict []sql.ConflictOption
}

// Save creates the AuditEvent entities in the database.
func (_c *AuditEventCreateBulk) Save(ctx context.Context) ([]*AuditEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEventCreateBulk) SaveX(ctx context.Context) []*AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuditEventUpsertBulk {
	_c.conflict = opts
	return &AuditEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditEventCreateBulk) OnConflictColumns(columns ...string) *AuditEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditEventUpsertBulk{
		create: _c,
	}
}

// AuditEventUpsertBulk is the builder for "upsert"-ing
// a bulk of AuditEvent nodes.
type AuditEventUpsertBulk struct {
	create *AuditEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditEventUpsertBulk) UpdateNewValues() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(auditevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(auditevent.FieldCreatedAt)
			}
			if _, exists := b.mutation.OutboxEventID(); exists {
				s.SetIgnore(auditevent.FieldOutboxEventID)
			}
			if _, exists := b.mutation.EventType(); exists {
				s.SetIgnore(auditevent.FieldEventType)
			}
			if _, exists := b.mutation.ActorID(); exists {
				s.SetIgnore(auditevent.FieldActorID)
			}
			if _, exists := b.mutation.OrganizationID(); exists {
				s.SetIgnore(auditevent.FieldOrganizationID)
			}
			if _, exists := b.mutation.ResourceType(); exists {
				s.SetIgnore(auditevent.FieldResourceType)
			}
			if _, exists := b.mutation.ResourceID(); exists {
				s.SetIgnore(auditevent.FieldResourceID)
			}
			if _, exists := b.mutation.Payload(); exists {
				s.SetIgnore(auditevent.FieldPayload)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuditEventUpsertBulk) Ignore() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditEventUpsertBulk) DoNothing() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditEventCreateBulk.OnConflict
// documentation for more info.
func (u *AuditEventUpsertBulk) Update(set func(*AuditEventUpsert)) *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuditEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuditEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
