// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/open-huddle/huddle/apps/api/ent/emaildelivery"
	"github.com/open-huddle/huddle/apps/api/ent/invitation"
)

// EmailDeliveryCreate is the builder for creating a EmailDelivery entity.
type EmailDeliveryCreate struct {
	config
	mutation *EmailDeliveryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailDeliveryCreate) SetCreatedAt(v time.Time) *EmailDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailDeliveryCreate) SetNillableCreatedAt(v *time.Time) *EmailDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EmailDeliveryCreate) SetStatus(v emaildelivery.Status) *EmailDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetFailureReason sets the "failure_reason" field.
func (_c *EmailDeliveryCreate) SetFailureReason(v string) *EmailDeliveryCreate {
	_c.mutation.SetFailureReason(v)
	return _c
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_c *EmailDeliveryCreate) SetNillableFailureReason(v *string) *EmailDeliveryCreate {
	if v != nil {
		_c.SetFailureReason(*v)
	}
	return _c
}

// SetRecipient sets the "recipient" field.
func (_c *EmailDeliveryCreate) SetRecipient(v string) *EmailDeliveryCreate {
	_c.mutation.SetRecipient(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EmailDeliveryCreate) SetID(v uuid.UUID) *EmailDeliveryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EmailDeliveryCreate) SetNillableID(v *uuid.UUID) *EmailDeliveryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetInvitationID sets the "invitation" edge to the Invitation entity by ID.
func (_c *EmailDeliveryCreate) SetInvitationID(id uuid.UUID) *EmailDeliveryCreate {
	_c.mutation.SetInvitationID(id)
	return _c
}

// SetInvitation sets the "invitation" edge to the Invitation entity.
func (_c *EmailDeliveryCreate) SetInvitation(v *Invitation) *EmailDeliveryCreate {
	return _c.SetInvitationID(v.ID)
}

// Mutation returns the EmailDeliveryMutation object of the builder.
func (_c *EmailDeliveryCreate) Mutation() *EmailDeliveryMutation {
	return _c.mutation
}

// Save creates the EmailDelivery in the database.
func (_c *EmailDeliveryCreate) Save(ctx context.Context) (*EmailDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailDeliveryCreate) SaveX(ctx context.Context) *EmailDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailDeliveryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emaildelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := emaildelivery.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailDeliveryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailDelivery.created_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EmailDelivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := emaildelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EmailDelivery.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Recipient(); !ok {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required field "EmailDelivery.recipient"`)}
	}
	if v, ok := _c.mutation.Recipient(); ok {
		if err := emaildelivery.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "EmailDelivery.recipient": %w`, err)}
		}
	}
	if len(_c.mutation.InvitationIDs()) == 0 {
		return &ValidationError{Name: "invitation", err: errors.New(`ent: missing required edge "EmailDelivery.invitation"`)}
	}
	return nil
}

func (_c *EmailDeliveryCreate) sqlSave(ctx context.Context) (*EmailDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailDeliveryCreate) createSpec() (*EmailDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emaildelivery.Table, sqlgraph.NewFieldSpec(emaildelivery.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emaildelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(emaildelivery.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FailureReason(); ok {
		_spec.SetField(emaildelivery.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = value
	}
	if value, ok := _c.mutation.Recipient(); ok {
		_spec.SetField(emaildelivery.FieldRecipient, field.TypeString, value)
		_node.Recipient = value
	}
	if nodes := _c.mutation.InvitationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   emaildelivery.InvitationTable,
			Columns: []string{emaildelivery.InvitationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.invitation_deliveries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailDelivery.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailDeliveryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailDeliveryCreate) OnConflict(opts ...sql.ConflictOption) *EmailDeliveryUpsertOne {
	_c.conflict = opts
	return &EmailDeliveryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailDeliveryCreate) OnConflictColumns(columns ...string) *EmailDeliveryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailDeliveryUpsertOne{
		create: _c,
	}
}

type (
	// EmailDeliveryUpsertOne is the builder for "upsert"-ing
	//  one EmailDelivery node.
	EmailDeliveryUpsertOne struct {
		create *EmailDeliveryCreate
	}

	// EmailDeliveryUpsert is the "OnConflict" setter.
	EmailDeliveryUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.EmailDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(emaildelivery.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailDeliveryUpsertOne) UpdateNewValues() *EmailDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(emaildelivery.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(emaildelivery.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Status(); exists {
			s.SetIgnore(emaildelivery.FieldStatus)
		}
		if _, exists := u.create.mutation.FailureReason(); exists {
			s.SetIgnore(emaildelivery.FieldFailureReason)
		}
		if _, exists := u.create.mutation.Recipient(); exists {
			s.SetIgnore(emaildelivery.FieldRecipient)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailDelivery.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailDeliveryUpsertOne) Ignore() *EmailDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailDeliveryUpsertOne) DoNothing() *EmailDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailDeliveryCreate.OnConflict
// documentation for more info.
func (u *EmailDeliveryUpsertOne) Update(set func(*EmailDeliveryUpsert)) *EmailDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *EmailDeliveryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailDeliveryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailDeliveryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailDeliveryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EmailDeliveryUpsertOne.ID is not supported by MySQL driver. Use EmailDeliveryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailDeliveryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailDeliveryCreateBulk is the builder for creating many EmailDelivery entities in bulk.
type EmailDeliveryCreateBulk struct {
	config
	err      error
	builders []*EmailDeliveryCreate
	conflict []sql.ConflictOption
}

// Save creates the EmailDelivery entities in the database.
func (_c *EmailDeliveryCreateBulk) Save(ctx context.Context) ([]*EmailDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailDeliveryCreateBulk) SaveX(ctx context.Context) []*EmailDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailDelivery.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailDeliveryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailDeliveryCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailDeliveryUpsertBulk {
	_c.conflict = opts
	return &EmailDeliveryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailDeliveryCreateBulk) OnConflictColumns(columns ...string) *EmailDeliveryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailDeliveryUpsertBulk{
		create: _c,
	}
}

// EmailDeliveryUpsertBulk is the builder for "upsert"-ing
// a bulk of EmailDelivery nodes.
type EmailDeliveryUpsertBulk struct {
	create *EmailDeliveryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmailDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(emaildelivery.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailDeliveryUpsertBulk) UpdateNewValues() *EmailDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(emaildelivery.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(emaildelivery.FieldCreatedAt)
			}
			if _, exists := b.mutation.Status(); exists {
				s.SetIgnore(emaildelivery.FieldStatus)
			}
			if _, exists := b.mutation.FailureReason(); exists {
				s.SetIgnore(emaildelivery.FieldFailureReason)
			}
			if _, exists := b.mutation.Recipient(); exists {
				s.SetIgnore(emaildelivery.FieldRecipient)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailDelivery.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailDeliveryUpsertBulk) Ignore() *EmailDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailDeliveryUpsertBulk) DoNothing() *EmailDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailDeliveryCreateBulk.OnConflict
// documentation for more info.
func (u *EmailDeliveryUpsertBulk) Update(set func(*EmailDeliveryUpsert)) *EmailDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *EmailDeliveryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailDeliveryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailDeliveryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailDeliveryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
