// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-huddle/huddle/apps/api/ent/emaildelivery"
	"github.com/open-huddle/huddle/apps/api/ent/predicate"
)

// EmailDeliveryUpdate is the builder for updating EmailDelivery entities.
type EmailDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *EmailDeliveryMutation
}

// Where appends a list predicates to the EmailDeliveryUpdate builder.
func (_u *EmailDeliveryUpdate) Where(ps ...predicate.EmailDelivery) *EmailDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the EmailDeliveryMutation object of the builder.
func (_u *EmailDeliveryUpdate) Mutation() *EmailDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailDeliveryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailDeliveryUpdate) check() error {
	if _u.mutation.InvitationCleared() && len(_u.mutation.InvitationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailDelivery.invitation"`)
	}
	return nil
}

func (_u *EmailDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emaildelivery.Table, emaildelivery.Columns, sqlgraph.NewFieldSpec(emaildelivery.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(emaildelivery.FieldFailureReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emaildelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailDeliveryUpdateOne is the builder for updating a single EmailDelivery entity.
type EmailDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailDeliveryMutation
}

// Mutation returns the EmailDeliveryMutation object of the builder.
func (_u *EmailDeliveryUpdateOne) Mutation() *EmailDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailDeliveryUpdate builder.
func (_u *EmailDeliveryUpdateOne) Where(ps ...predicate.EmailDelivery) *EmailDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailDeliveryUpdateOne) Select(field string, fields ...string) *EmailDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailDelivery entity.
func (_u *EmailDeliveryUpdateOne) Save(ctx context.Context) (*EmailDelivery, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailDeliveryUpdateOne) SaveX(ctx context.Context) *EmailDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailDeliveryUpdateOne) check() error {
	if _u.mutation.InvitationCleared() && len(_u.mutation.InvitationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailDelivery.invitation"`)
	}
	return nil
}

func (_u *EmailDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *EmailDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emaildelivery.Table, emaildelivery.Columns, sqlgraph.NewFieldSpec(emaildelivery.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emaildelivery.FieldID)
		for _, f := range fields {
			if !emaildelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emaildelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(emaildelivery.FieldFailureReason, field.TypeString)
	}
	_node = &EmailDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emaildelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
