// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-huddle/huddle/apps/api/ent/messagemention"
	"github.com/open-huddle/huddle/apps/api/ent/predicate"
)

// MessageMentionUpdate is the builder for updating MessageMention entities.
type MessageMentionUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMentionMutation
}

// Where appends a list predicates to the MessageMentionUpdate builder.
func (_u *MessageMentionUpdate) Where(ps ...predicate.MessageMention) *MessageMentionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the MessageMentionMutation object of the builder.
func (_u *MessageMentionUpdate) Mutation() *MessageMentionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageMentionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageMentionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageMentionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageMentionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageMentionUpdate) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageMention.message"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageMention.user"`)
	}
	return nil
}

func (_u *MessageMentionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagemention.Table, messagemention.Columns, sqlgraph.NewFieldSpec(messagemention.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagemention.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageMentionUpdateOne is the builder for updating a single MessageMention entity.
type MessageMentionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMentionMutation
}

// Mutation returns the MessageMentionMutation object of the builder.
func (_u *MessageMentionUpdateOne) Mutation() *MessageMentionMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageMentionUpdate builder.
func (_u *MessageMentionUpdateOne) Where(ps ...predicate.MessageMention) *MessageMentionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageMentionUpdateOne) Select(field string, fields ...string) *MessageMentionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MessageMention entity.
func (_u *MessageMentionUpdateOne) Save(ctx context.Context) (*MessageMention, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageMentionUpdateOne) SaveX(ctx context.Context) *MessageMention {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageMentionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageMentionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageMentionUpdateOne) check() error {
	if _u.mutation.MessageCleared() && len(_u.mutation.MessageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageMention.message"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessageMention.user"`)
	}
	return nil
}

func (_u *MessageMentionUpdateOne) sqlSave(ctx context.Context) (_node *MessageMention, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagemention.Table, messagemention.Columns, sqlgraph.NewFieldSpec(messagemention.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageMention.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagemention.FieldID)
		for _, f := range fields {
			if !messagemention.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messagemention.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &MessageMention{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagemention.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
