// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/open-huddle/huddle/apps/api/ent/notificationpreference"
	"github.com/open-huddle/huddle/apps/api/ent/user"
)

// NotificationPreferenceCreate is the builder for creating a NotificationPreference entity.
type NotificationPreferenceCreate struct {
	config
	mutation *NotificationPreferenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationPreferenceCreate) SetCreatedAt(v time.Time) *NotificationPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableCreatedAt(v *time.Time) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationPreferenceCreate) SetUpdatedAt(v time.Time) *NotificationPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NotificationPreferenceCreate) SetUserID(v uuid.UUID) *NotificationPreferenceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *NotificationPreferenceCreate) SetKind(v notificationpreference.Kind) *NotificationPreferenceCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetEmailEnabled sets the "email_enabled" field.
func (_c *NotificationPreferenceCreate) SetEmailEnabled(v bool) *NotificationPreferenceCreate {
	_c.mutation.SetEmailEnabled(v)
	return _c
}

// SetNillableEmailEnabled sets the "email_enabled" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableEmailEnabled(v *bool) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetEmailEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationPreferenceCreate) SetID(v uuid.UUID) *NotificationPreferenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableID(v *uuid.UUID) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *NotificationPreferenceCreate) SetUser(v *User) *NotificationPreferenceCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the NotificationPreferenceMutation object of the builder.
func (_c *NotificationPreferenceCreate) Mutation() *NotificationPreferenceMutation {
	return _c.mutation
}

// Save creates the NotificationPreference in the database.
func (_c *NotificationPreferenceCreate) Save(ctx context.Context) (*NotificationPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationPreferenceCreate) SaveX(ctx context.Context) *NotificationPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationPreferenceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notificationpreference.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notificationpreference.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EmailEnabled(); !ok {
		v := notificationpreference.DefaultEmailEnabled
		_c.mutation.SetEmailEnabled(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notificationpreference.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationPreferenceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationPreference.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationPreference.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NotificationPreference.user_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "NotificationPreference.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := notificationpreference.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationPreference.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmailEnabled(); !ok {
		return &ValidationError{Name: "email_enabled", err: errors.New(`ent: missing required field "NotificationPreference.email_enabled"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "NotificationPreference.user"`)}
	}
	return nil
}

func (_c *NotificationPreferenceCreate) sqlSave(ctx context.Context) (*NotificationPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationPreferenceCreate) createSpec() (*NotificationPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationpreference.Table, sqlgraph.NewFieldSpec(notificationpreference.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationpreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationpreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(notificationpreference.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.EmailEnabled(); ok {
		_spec.SetField(notificationpreference.FieldEmailEnabled, field.TypeBool, value)
		_node.EmailEnabled = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationpreference.UserTable,
			Columns: []string{notificationpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationPreference.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationPreferenceCreate) OnConflict(opts ...sql.ConflictOption) *NotificationPreferenceUpsertOne {
	_c.conflict = opts
	return &NotificationPreferenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationPreferenceCreate) OnConflictColumns(columns ...string) *NotificationPreferenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationPreferenceUpsertOne{
		create: _c,
	}
}

type (
	// NotificationPreferenceUpsertOne is the builder for "upsert"-ing
	//  one NotificationPreference node.
	NotificationPreferenceUpsertOne struct {
		create *NotificationPreferenceCreate
	}

	// NotificationPreferenceUpsert is the "OnConflict" setter.
	NotificationPreferenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationPreferenceUpsert) SetUpdatedAt(v time.Time) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateUpdatedAt() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldUpdatedAt)
	return u
}

// SetEmailEnabled sets the "email_enabled" field.
func (u *NotificationPreferenceUpsert) SetEmailEnabled(v bool) *NotificationPreferenceUpsert {
	u.Set(notificationpreference.FieldEmailEnabled, v)
	return u
}

// UpdateEmailEnabled sets the "email_enabled" field to the value that was provided on create.
func (u *NotificationPreferenceUpsert) UpdateEmailEnabled() *NotificationPreferenceUpsert {
	u.SetExcluded(notificationpreference.FieldEmailEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationpreference.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationPreferenceUpsertOne) UpdateNewValues() *NotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationpreference.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(notificationpreference.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(notificationpreference.FieldUserID)
		}
		if _, exists := u.create.mutation.Kind(); exists {
			s.SetIgnore(notificationpreference.FieldKind)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationPreferenceUpsertOne) Ignore() *NotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationPreferenceUpsertOne) DoNothing() *NotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationPreferenceCreate.OnConflict
// documentation for more info.
func (u *NotificationPreferenceUpsertOne) Update(set func(*NotificationPreferenceUpsert)) *NotificationPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationPreferenceUpsertOne) SetUpdatedAt(v time.Time) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateUpdatedAt() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmailEnabled sets the "email_enabled" field.
func (u *NotificationPreferenceUpsertOne) SetEmailEnabled(v bool) *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetEmailEnabled(v)
	})
}

// UpdateEmailEnabled sets the "email_enabled" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertOne) UpdateEmailEnabled() *NotificationPreferenceUpsertOne {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateEmailEnabled()
	})
}

// Exec executes the query.
func (u *NotificationPreferenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationPreferenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationPreferenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationPreferenceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NotificationPreferenceUpsertOne.ID is not supported by MySQL driver. Use NotificationPreferenceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationPreferenceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationPreferenceCreateBulk is the builder for creating many NotificationPreference entities in bulk.
type NotificationPreferenceCreateBulk struct {
	config
	err      error
	builders []*NotificationPreferenceCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationPreference entities in the database.
func (_c *NotificationPreferenceCreateBulk) Save(ctx context.Context) ([]*NotificationPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationPreferenceCreateBulk) SaveX(ctx context.Context) []*NotificationPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationPreference.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationPreferenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationPreferenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationPreferenceUpsertBulk {
	_c.conflict = opts
	return &NotificationPreferenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationPreferenceCreateBulk) OnConflictColumns(columns ...string) *NotificationPreferenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationPreferenceUpsertBulk{
		create: _c,
	}
}

// NotificationPreferenceUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationPreference nodes.
type NotificationPreferenceUpsertBulk struct {
	create *NotificationPreferenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationpreference.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationPreferenceUpsertBulk) UpdateNewValues() *NotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationpreference.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(notificationpreference.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(notificationpreference.FieldUserID)
			}
			if _, exists := b.mutation.Kind(); exists {
				s.SetIgnore(notificationpreference.FieldKind)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationPreference.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationPreferenceUpsertBulk) Ignore() *NotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationPreferenceUpsertBulk) DoNothing() *NotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationPreferenceCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationPreferenceUpsertBulk) Update(set func(*NotificationPreferenceUpsert)) *NotificationPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationPreferenceUpsertBulk) SetUpdatedAt(v time.Time) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateUpdatedAt() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmailEnabled sets the "email_enabled" field.
func (u *NotificationPreferenceUpsertBulk) SetEmailEnabled(v bool) *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.SetEmailEnabled(v)
	})
}

// UpdateEmailEnabled sets the "email_enabled" field to the value that was provided on create.
func (u *NotificationPreferenceUpsertBulk) UpdateEmailEnabled() *NotificationPreferenceUpsertBulk {
	return u.Update(func(s *NotificationPreferenceUpsert) {
		s.UpdateEmailEnabled()
	})
}

// Exec executes the query.
func (u *NotificationPreferenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationPreferenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationPreferenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationPreferenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
