// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/open-huddle/huddle/apps/api/ent/auditevent"
	"github.com/open-huddle/huddle/apps/api/ent/outboxevent"
)

// OutboxEventCreate is the builder for creating a OutboxEvent entity.
type OutboxEventCreate struct {
	config
	mutation *OutboxEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OutboxEventCreate) SetCreatedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableCreatedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAggregateType sets the "aggregate_type" field.
func (_c *OutboxEventCreate) SetAggregateType(v string) *OutboxEventCreate {
	_c.mutation.SetAggregateType(v)
	return _c
}

// SetAggregateID sets the "aggregate_id" field.
func (_c *OutboxEventCreate) SetAggregateID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetAggregateID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *OutboxEventCreate) SetEventType(v string) *OutboxEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *OutboxEventCreate) SetSubject(v string) *OutboxEventCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *OutboxEventCreate) SetPayload(v []byte) *OutboxEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *OutboxEventCreate) SetActorID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableActorID(v *uuid.UUID) *OutboxEventCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *OutboxEventCreate) SetOrganizationID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableOrganizationID(v *uuid.UUID) *OutboxEventCreate {
	if v != nil {
		_c.SetOrganizationID(*v)
	}
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *OutboxEventCreate) SetResourceType(v string) *OutboxEventCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *OutboxEventCreate) SetResourceID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *OutboxEventCreate) SetPublishedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillablePublishedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetIndexedAt sets the "indexed_at" field.
func (_c *OutboxEventCreate) SetIndexedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetIndexedAt(v)
	return _c
}

// SetNillableIndexedAt sets the "indexed_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableIndexedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetIndexedAt(*v)
	}
	return _c
}

// SetNotifiedAt sets the "notified_at" field.
func (_c *OutboxEventCreate) SetNotifiedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetNotifiedAt(v)
	return _c
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableNotifiedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetNotifiedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OutboxEventCreate) SetID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableID(v *uuid.UUID) *OutboxEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAuditEventID sets the "audit_event" edge to the AuditEvent entity by ID.
func (_c *OutboxEventCreate) SetAuditEventID(id uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetAuditEventID(id)
	return _c
}

// SetNillableAuditEventID sets the "audit_event" edge to the AuditEvent entity by ID if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableAuditEventID(id *uuid.UUID) *OutboxEventCreate {
	if id != nil {
		_c = _c.SetAuditEventID(*id)
	}
	return _c
}

// SetAuditEvent sets the "audit_event" edge to the AuditEvent entity.
func (_c *OutboxEventCreate) SetAuditEvent(v *AuditEvent) *OutboxEventCreate {
	return _c.SetAuditEventID(v.ID)
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_c *OutboxEventCreate) Mutation() *OutboxEventMutation {
	return _c.mutation
}

// Save creates the OutboxEvent in the database.
func (_c *OutboxEventCreate) Save(ctx context.Context) (*OutboxEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutboxEventCreate) SaveX(ctx context.Context) *OutboxEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutboxEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := outboxevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := outboxevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutboxEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OutboxEvent.created_at"`)}
	}
	if _, ok := _c.mutation.AggregateType(); !ok {
		return &ValidationError{Name: "aggregate_type", err: errors.New(`ent: missing required field "OutboxEvent.aggregate_type"`)}
	}
	if v, ok := _c.mutation.AggregateType(); ok {
		if err := outboxevent.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.aggregate_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AggregateID(); !ok {
		return &ValidationError{Name: "aggregate_id", err: errors.New(`ent: missing required field "OutboxEvent.aggregate_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "OutboxEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := outboxevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "OutboxEvent.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := outboxevent.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "OutboxEvent.payload"`)}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "OutboxEvent.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := outboxevent.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "OutboxEvent.resource_id"`)}
	}
	return nil
}

func (_c *OutboxEventCreate) sqlSave(ctx context.Context) (*OutboxEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutboxEventCreate) createSpec() (*OutboxEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &OutboxEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(outboxevent.Table, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(outboxevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.AggregateType(); ok {
		_spec.SetField(outboxevent.FieldAggregateType, field.TypeString, value)
		_node.AggregateType = value
	}
	if value, ok := _c.mutation.AggregateID(); ok {
		_spec.SetField(outboxevent.FieldAggregateID, field.TypeUUID, value)
		_node.AggregateID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(outboxevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(outboxevent.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(outboxevent.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(outboxevent.FieldActorID, field.TypeUUID, value)
		_node.ActorID = &value
	}
	if value, ok := _c.mutation.OrganizationID(); ok {
		_spec.SetField(outboxevent.FieldOrganizationID, field.TypeUUID, value)
		_node.OrganizationID = &value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(outboxevent.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(outboxevent.FieldResourceID, field.TypeUUID, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(outboxevent.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.IndexedAt(); ok {
		_spec.SetField(outboxevent.FieldIndexedAt, field.TypeTime, value)
		_node.IndexedAt = &value
	}
	if value, ok := _c.mutation.NotifiedAt(); ok {
		_spec.SetField(outboxevent.FieldNotifiedAt, field.TypeTime, value)
		_node.NotifiedAt = &value
	}
	if nodes := _c.mutation.AuditEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   outboxevent.AuditEventTable,
			Columns: []string{outboxevent.AuditEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OutboxEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OutboxEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OutboxEventCreate) OnConflict(opts ...sql.ConflictOption) *OutboxEventUpsertOne {
	_c.conflict = opts
	return &OutboxEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OutboxEventCreate) OnConflictColumns(columns ...string) *OutboxEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OutboxEventUpsertOne{
		create: _c,
	}
}

type (
	// OutboxEventUpsertOne is the builder for "upsert"-ing
	//  one OutboxEvent node.
	OutboxEventUpsertOne struct {
		create *OutboxEventCreate
	}

	// OutboxEventUpsert is the "OnConflict" setter.
	OutboxEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetPublishedAt sets the "published_at" field.
func (u *OutboxEventUpsert) SetPublishedAt(v time.Time) *OutboxEventUpsert {
	u.Set(outboxevent.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdatePublishedAt() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *OutboxEventUpsert) ClearPublishedAt() *OutboxEventUpsert {
	u.SetNull(outboxevent.FieldPublishedAt)
	return u
}

// SetIndexedAt sets the "indexed_at" field.
func (u *OutboxEventUpsert) SetIndexedAt(v time.Time) *OutboxEventUpsert {
	u.Set(outboxevent.FieldIndexedAt, v)
	return u
}

// UpdateIndexedAt sets the "indexed_at" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateIndexedAt() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldIndexedAt)
	return u
}

// ClearIndexedAt clears the value of the "indexed_at" field.
func (u *OutboxEventUpsert) ClearIndexedAt() *OutboxEventUpsert {
	u.SetNull(outboxevent.FieldIndexedAt)
	return u
}

// SetNotifiedAt sets the "notified_at" field.
func (u *OutboxEventUpsert) SetNotifiedAt(v time.Time) *OutboxEventUpsert {
	u.Set(outboxevent.FieldNotifiedAt, v)
	return u
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateNotifiedAt() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldNotifiedAt)
	return u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *OutboxEventUpsert) ClearNotifiedAt() *OutboxEventUpsert {
	u.SetNull(outboxevent.FieldNotifiedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(outboxevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OutboxEventUpsertOne) UpdateNewValues() *OutboxEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(outboxevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(outboxevent.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.AggregateType(); exists {
			s.SetIgnore(outboxevent.FieldAggregateType)
		}
		if _, exists := u.create.mutation.AggregateID(); exists {
			s.SetIgnore(outboxevent.FieldAggregateID)
		}
		if _, exists := u.create.mutation.EventType(); exists {
			s.SetIgnore(outboxevent.FieldEventType)
		}
		if _, exists := u.create.mutation.Subject(); exists {
			s.SetIgnore(outboxevent.FieldSubject)
		}
		if _, exists := u.create.mutation.Payload(); exists {
			s.SetIgnore(outboxevent.FieldPayload)
		}
		if _, exists := u.create.mutation.ActorID(); exists {
			s.SetIgnore(outboxevent.FieldActorID)
		}
		if _, exists := u.create.mutation.OrganizationID(); exists {
			s.SetIgnore(outboxevent.FieldOrganizationID)
		}
		if _, exists := u.create.mutation.ResourceType(); exists {
			s.SetIgnore(outboxevent.FieldResourceType)
		}
		if _, exists := u.create.mutation.ResourceID(); exists {
			s.SetIgnore(outboxevent.FieldResourceID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OutboxEventUpsertOne) Ignore() *OutboxEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OutboxEventUpsertOne) DoNothing() *OutboxEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OutboxEventCreate.OnConflict
// documentation for more info.
func (u *OutboxEventUpsertOne) Update(set func(*OutboxEventUpsert)) *OutboxEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OutboxEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *OutboxEventUpsertOne) SetPublishedAt(v time.Time) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdatePublishedAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *OutboxEventUpsertOne) ClearPublishedAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.ClearPublishedAt()
	})
}

// SetIndexedAt sets the "indexed_at" field.
func (u *OutboxEventUpsertOne) SetIndexedAt(v time.Time) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetIndexedAt(v)
	})
}

// UpdateIndexedAt sets the "indexed_at" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateIndexedAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateIndexedAt()
	})
}

// ClearIndexedAt clears the value of the "indexed_at" field.
func (u *OutboxEventUpsertOne) ClearIndexedAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.ClearIndexedAt()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *OutboxEventUpsertOne) SetNotifiedAt(v time.Time) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateNotifiedAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateNotifiedAt()
	})
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *OutboxEventUpsertOne) ClearNotifiedAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.ClearNotifiedAt()
	})
}

// Exec executes the query.
func (u *OutboxEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OutboxEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OutboxEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OutboxEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OutboxEventUpsertOne.ID is not supported by MySQL driver. Use OutboxEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OutboxEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OutboxEventCreateBulk is the builder for creating many OutboxEvent entities in bulk.
type OutboxEventCreateBulk struct {
	config
	err      error
	builders []*OutboxEventCreate
	conflict []sql.ConflictOption
}

// Save creates the OutboxEvent entities in the database.
func (_c *OutboxEventCreateBulk) Save(ctx context.Context) ([]*OutboxEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OutboxEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutboxEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutboxEventCreateBulk) SaveX(ctx context.Context) []*OutboxEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OutboxEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OutboxEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OutboxEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *OutboxEventUpsertBulk {
	_c.conflict = opts
	return &OutboxEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OutboxEventCreateBulk) OnConflictColumns(columns ...string) *OutboxEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OutboxEventUpsertBulk{
		create: _c,
	}
}

// OutboxEventUpsertBulk is the builder for "upsert"-ing
// a bulk of OutboxEvent nodes.
type OutboxEventUpsertBulk struct {
	create *OutboxEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(outboxevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OutboxEventUpsertBulk) UpdateNewValues() *OutboxEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(outboxevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(outboxevent.FieldCreatedAt)
			}
			if _, exists := b.mutation.AggregateType(); exists {
				s.SetIgnore(outboxevent.FieldAggregateType)
			}
			if _, exists := b.mutation.AggregateID(); exists {
				s.SetIgnore(outboxevent.FieldAggregateID)
			}
			if _, exists := b.mutation.EventType(); exists {
				s.SetIgnore(outboxevent.FieldEventType)
			}
			if _, exists := b.mutation.Subject(); exists {
				s.SetIgnore(outboxevent.FieldSubject)
			}
			if _, exists := b.mutation.Payload(); exists {
				s.SetIgnore(outboxevent.FieldPayload)
			}
			if _, exists := b.mutation.ActorID(); exists {
				s.SetIgnore(outboxevent.FieldActorID)
			}
			if _, exists := b.mutation.OrganizationID(); exists {
				s.SetIgnore(outboxevent.FieldOrganizationID)
			}
			if _, exists := b.mutation.ResourceType(); exists {
				s.SetIgnore(outboxevent.FieldResourceType)
			}
			if _, exists := b.mutation.ResourceID(); exists {
				s.SetIgnore(outboxevent.FieldResourceID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OutboxEventUpsertBulk) Ignore() *OutboxEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OutboxEventUpsertBulk) DoNothing() *OutboxEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OutboxEventCreateBulk.OnConflict
// documentation for more info.
func (u *OutboxEventUpsertBulk) Update(set func(*OutboxEventUpsert)) *OutboxEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OutboxEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *OutboxEventUpsertBulk) SetPublishedAt(v time.Time) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdatePublishedAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *OutboxEventUpsertBulk) ClearPublishedAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.ClearPublishedAt()
	})
}

// SetIndexedAt sets the "indexed_at" field.
func (u *OutboxEventUpsertBulk) SetIndexedAt(v time.Time) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetIndexedAt(v)
	})
}

// UpdateIndexedAt sets the "indexed_at" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateIndexedAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateIndexedAt()
	})
}

// ClearIndexedAt clears the value of the "indexed_at" field.
func (u *OutboxEventUpsertBulk) ClearIndexedAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.ClearIndexedAt()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *OutboxEventUpsertBulk) SetNotifiedAt(v time.Time) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateNotifiedAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateNotifiedAt()
	})
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *OutboxEventUpsertBulk) ClearNotifiedAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.ClearNotifiedAt()
	})
}

// Exec executes the query.
func (u *OutboxEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OutboxEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OutboxEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OutboxEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
