// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/open-huddle/huddle/apps/api/ent/auditevent"
	"github.com/open-huddle/huddle/apps/api/ent/channel"
	"github.com/open-huddle/huddle/apps/api/ent/emaildelivery"
	"github.com/open-huddle/huddle/apps/api/ent/invitation"
	"github.com/open-huddle/huddle/apps/api/ent/membership"
	"github.com/open-huddle/huddle/apps/api/ent/message"
	"github.com/open-huddle/huddle/apps/api/ent/organization"
	"github.com/open-huddle/huddle/apps/api/ent/outboxevent"
	"github.com/open-huddle/huddle/apps/api/ent/schema"
	"github.com/open-huddle/huddle/apps/api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditeventMixin := schema.AuditEvent{}.Mixin()
	auditeventMixinFields0 := auditeventMixin[0].Fields()
	_ = auditeventMixinFields0
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescCreatedAt is the schema descriptor for created_at field.
	auditeventDescCreatedAt := auditeventFields[0].Descriptor()
	// auditevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditevent.DefaultCreatedAt = auditeventDescCreatedAt.Default.(func() time.Time)
	// auditeventDescEventType is the schema descriptor for event_type field.
	auditeventDescEventType := auditeventFields[2].Descriptor()
	// auditevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	auditevent.EventTypeValidator = auditeventDescEventType.Validators[0].(func(string) error)
	// auditeventDescResourceType is the schema descriptor for resource_type field.
	auditeventDescResourceType := auditeventFields[5].Descriptor()
	// auditevent.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	auditevent.ResourceTypeValidator = auditeventDescResourceType.Validators[0].(func(string) error)
	// auditeventDescID is the schema descriptor for id field.
	auditeventDescID := auditeventMixinFields0[0].Descriptor()
	// auditevent.DefaultID holds the default value on creation for the id field.
	auditevent.DefaultID = auditeventDescID.Default.(func() uuid.UUID)
	channelMixin := schema.Channel{}.Mixin()
	channelMixinFields0 := channelMixin[0].Fields()
	_ = channelMixinFields0
	channelMixinFields1 := channelMixin[1].Fields()
	_ = channelMixinFields1
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescCreatedAt is the schema descriptor for created_at field.
	channelDescCreatedAt := channelMixinFields1[0].Descriptor()
	// channel.DefaultCreatedAt holds the default value on creation for the created_at field.
	channel.DefaultCreatedAt = channelDescCreatedAt.Default.(func() time.Time)
	// channelDescUpdatedAt is the schema descriptor for updated_at field.
	channelDescUpdatedAt := channelMixinFields1[1].Descriptor()
	// channel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	channel.DefaultUpdatedAt = channelDescUpdatedAt.Default.(func() time.Time)
	// channel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	channel.UpdateDefaultUpdatedAt = channelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// channelDescName is the schema descriptor for name field.
	channelDescName := channelFields[0].Descriptor()
	// channel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	channel.NameValidator = channelDescName.Validators[0].(func(string) error)
	// channelDescSlug is the schema descriptor for slug field.
	channelDescSlug := channelFields[1].Descriptor()
	// channel.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	channel.SlugValidator = channelDescSlug.Validators[0].(func(string) error)
	// channelDescID is the schema descriptor for id field.
	channelDescID := channelMixinFields0[0].Descriptor()
	// channel.DefaultID holds the default value on creation for the id field.
	channel.DefaultID = channelDescID.Default.(func() uuid.UUID)
	emaildeliveryMixin := schema.EmailDelivery{}.Mixin()
	emaildeliveryMixinFields0 := emaildeliveryMixin[0].Fields()
	_ = emaildeliveryMixinFields0
	emaildeliveryFields := schema.EmailDelivery{}.Fields()
	_ = emaildeliveryFields
	// emaildeliveryDescCreatedAt is the schema descriptor for created_at field.
	emaildeliveryDescCreatedAt := emaildeliveryFields[0].Descriptor()
	// emaildelivery.DefaultCreatedAt holds the default value on creation for the created_at field.
	emaildelivery.DefaultCreatedAt = emaildeliveryDescCreatedAt.Default.(func() time.Time)
	// emaildeliveryDescRecipient is the schema descriptor for recipient field.
	emaildeliveryDescRecipient := emaildeliveryFields[3].Descriptor()
	// emaildelivery.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	emaildelivery.RecipientValidator = emaildeliveryDescRecipient.Validators[0].(func(string) error)
	// emaildeliveryDescID is the schema descriptor for id field.
	emaildeliveryDescID := emaildeliveryMixinFields0[0].Descriptor()
	// emaildelivery.DefaultID holds the default value on creation for the id field.
	emaildelivery.DefaultID = emaildeliveryDescID.Default.(func() uuid.UUID)
	invitationMixin := schema.Invitation{}.Mixin()
	invitationMixinFields0 := invitationMixin[0].Fields()
	_ = invitationMixinFields0
	invitationMixinFields1 := invitationMixin[1].Fields()
	_ = invitationMixinFields1
	invitationFields := schema.Invitation{}.Fields()
	_ = invitationFields
	// invitationDescCreatedAt is the schema descriptor for created_at field.
	invitationDescCreatedAt := invitationMixinFields1[0].Descriptor()
	// invitation.DefaultCreatedAt holds the default value on creation for the created_at field.
	invitation.DefaultCreatedAt = invitationDescCreatedAt.Default.(func() time.Time)
	// invitationDescUpdatedAt is the schema descriptor for updated_at field.
	invitationDescUpdatedAt := invitationMixinFields1[1].Descriptor()
	// invitation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invitation.DefaultUpdatedAt = invitationDescUpdatedAt.Default.(func() time.Time)
	// invitation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invitation.UpdateDefaultUpdatedAt = invitationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// invitationDescEmail is the schema descriptor for email field.
	invitationDescEmail := invitationFields[0].Descriptor()
	// invitation.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	invitation.EmailValidator = invitationDescEmail.Validators[0].(func(string) error)
	// invitationDescTokenHash is the schema descriptor for token_hash field.
	invitationDescTokenHash := invitationFields[2].Descriptor()
	// invitation.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	invitation.TokenHashValidator = invitationDescTokenHash.Validators[0].(func([]byte) error)
	// invitationDescID is the schema descriptor for id field.
	invitationDescID := invitationMixinFields0[0].Descriptor()
	// invitation.DefaultID holds the default value on creation for the id field.
	invitation.DefaultID = invitationDescID.Default.(func() uuid.UUID)
	membershipMixin := schema.Membership{}.Mixin()
	membershipMixinFields0 := membershipMixin[0].Fields()
	_ = membershipMixinFields0
	membershipMixinFields1 := membershipMixin[1].Fields()
	_ = membershipMixinFields1
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescCreatedAt is the schema descriptor for created_at field.
	membershipDescCreatedAt := membershipMixinFields1[0].Descriptor()
	// membership.DefaultCreatedAt holds the default value on creation for the created_at field.
	membership.DefaultCreatedAt = membershipDescCreatedAt.Default.(func() time.Time)
	// membershipDescUpdatedAt is the schema descriptor for updated_at field.
	membershipDescUpdatedAt := membershipMixinFields1[1].Descriptor()
	// membership.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membership.DefaultUpdatedAt = membershipDescUpdatedAt.Default.(func() time.Time)
	// membership.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membership.UpdateDefaultUpdatedAt = membershipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membershipDescID is the schema descriptor for id field.
	membershipDescID := membershipMixinFields0[0].Descriptor()
	// membership.DefaultID holds the default value on creation for the id field.
	membership.DefaultID = membershipDescID.Default.(func() uuid.UUID)
	messageMixin := schema.Message{}.Mixin()
	messageMixinFields0 := messageMixin[0].Fields()
	_ = messageMixinFields0
	messageMixinFields1 := messageMixin[1].Fields()
	_ = messageMixinFields1
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageMixinFields1[0].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageMixinFields1[1].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// messageDescBody is the schema descriptor for body field.
	messageDescBody := messageFields[2].Descriptor()
	// message.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	message.BodyValidator = func() func(string) error {
		validators := messageDescBody.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(body string) error {
			for _, fn := range fns {
				if err := fn(body); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageMixinFields0[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationMixinFields1 := organizationMixin[1].Fields()
	_ = organizationMixinFields1
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields1[0].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields1[1].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[0].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescSlug is the schema descriptor for slug field.
	organizationDescSlug := organizationFields[1].Descriptor()
	// organization.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	organization.SlugValidator = organizationDescSlug.Validators[0].(func(string) error)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationMixinFields0[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	outboxeventMixin := schema.OutboxEvent{}.Mixin()
	outboxeventMixinFields0 := outboxeventMixin[0].Fields()
	_ = outboxeventMixinFields0
	outboxeventFields := schema.OutboxEvent{}.Fields()
	_ = outboxeventFields
	// outboxeventDescCreatedAt is the schema descriptor for created_at field.
	outboxeventDescCreatedAt := outboxeventFields[0].Descriptor()
	// outboxevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxevent.DefaultCreatedAt = outboxeventDescCreatedAt.Default.(func() time.Time)
	// outboxeventDescAggregateType is the schema descriptor for aggregate_type field.
	outboxeventDescAggregateType := outboxeventFields[1].Descriptor()
	// outboxevent.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	outboxevent.AggregateTypeValidator = outboxeventDescAggregateType.Validators[0].(func(string) error)
	// outboxeventDescEventType is the schema descriptor for event_type field.
	outboxeventDescEventType := outboxeventFields[3].Descriptor()
	// outboxevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	outboxevent.EventTypeValidator = outboxeventDescEventType.Validators[0].(func(string) error)
	// outboxeventDescSubject is the schema descriptor for subject field.
	outboxeventDescSubject := outboxeventFields[4].Descriptor()
	// outboxevent.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	outboxevent.SubjectValidator = outboxeventDescSubject.Validators[0].(func(string) error)
	// outboxeventDescResourceType is the schema descriptor for resource_type field.
	outboxeventDescResourceType := outboxeventFields[8].Descriptor()
	// outboxevent.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	outboxevent.ResourceTypeValidator = outboxeventDescResourceType.Validators[0].(func(string) error)
	// outboxeventDescID is the schema descriptor for id field.
	outboxeventDescID := outboxeventMixinFields0[0].Descriptor()
	// outboxevent.DefaultID holds the default value on creation for the id field.
	outboxevent.DefaultID = outboxeventDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescSubject is the schema descriptor for subject field.
	userDescSubject := userFields[0].Descriptor()
	// user.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	user.SubjectValidator = userDescSubject.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
